### ISSUE TITLE
Circular connections will cause the page to crash

### ISSUE THREAD

**Issue by Reekin** [emilwidlund/nodl#45]
I yarn dev the react-example project and tried connecting a color outpin to its parent's color inpin, and got an error.

Compiled with problems:
×
ERROR
[MobX] invalid action stack. did you forget to finish an action?
    at die (http://localhost:3000/bundle.js:14092:11)
    at _endAction (http://localhost:3000/bundle.js:15128:5)
    at executeAction (http://localhost:3000/bundle.js:15086:5)
    at Output.connect (http://localhost:3000/bundle.js:15069:12)
    at at.commitDraftConnection (http://localhost:3000/bundle.js:72406:1679)
    at Be (http://localhost:3000/bundle.js:72394:83826)
    at at.commitDraftConnection (http://localhost:3000/bundle.js:72394:83670)
    at http://localhost:3000/bundle.js:72477:760
    at HTMLUnknownElement.callCallback (http://localhost:3000/bundle.js:24584:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/bundle.js:24633:16)
ERROR
[MobX] invalid action stack. did you forget to finish an action?
    at die (http://localhost:3000/bundle.js:14092:11)
    at _endAction (http://localhost:3000/bundle.js:15128:5)
    at executeAction (http://localhost:3000/bundle.js:15086:5)
    at Output.connect (http://localhost:3000/bundle.js:15069:12)
    at at.commitDraftConnection (http://localhost:3000/bundle.js:72406:1679)
    at Be (http://localhost:3000/bundle.js:72394:83826)
    at at.commitDraftConnection (http://localhost:3000/bundle.js:72394:83670)
    at http://localhost:3000/bundle.js:72477:760
    at HTMLUnknownElement.callCallback (http://localhost:3000/bundle.js:24584:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/bundle.js:24633:16)
ERROR
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at __webpack_modules__.../../node_modules/rxjs/dist/cjs/internal/Subscriber.js.ConsumerObserver.next (http://localhost:3000/bundle.js:56367:17)
    at __webpack_modules__.../../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber._next (http://localhost:3000/bundle.js:56331:26)
    at __webpack_modules__.../../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next (http://localhost:3000/bundle.js:56302:18)
    at http://localhost:3000/bundle.js:56120:34
    at Object.errorContext (http://localhost:3000/bundle.js:64334:9)
    at __webpack_modules__.../../node_modules/rxjs/dist/cjs/internal/Subject.js.Subject.next (http://localhost:3000/bundle.js:56110:24)
    at __webpack_modules__.../../node_modules/rxjs/dist/cjs/internal/ReplaySubject.js.ReplaySubject.next (http://localhost:3000/bundle.js:55982:31)
    at __webpack_modules__.../../node_modules/rxjs/dist/cjs/internal/Subscriber.js.ConsumerObserver.next (http://localhost:3000/bundle.js:56364:33)
    at __webpack_modules__.../../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber._next (http://localhost:3000/bundle.js:56331:26)
    at __webpack_modules__.../../node_modules/rxjs/dist/cjs/internal/Subscriber.js.Subscriber.next (http://localhost:3000/bundle.js:56302:18)

![image](https://github.com/emilwidlund/nodl/assets/29672213/bdec30a0-0762-4071-bb1c-231811a50ae2)

**Comment by Reekin** [comment]
I want to use it to implement a flow graph without data observation, but the observable param is indispensable. That's a little awkward.
